config/routes.rb
Rails.application.routes.draw do
  
  get 'user/:id/edit',to: 'users#edit'
  delete 'user/:id',to: 'users#destroy'
  patch 'user/:id',to: 'users#update', as: :user
get 'user/sign_out'to: 'users#sign_out' 
  get 'user/index',to: 'users#index'
get 'users/new',to: 'users#new'
post 'users',to: 'users#create'
get 'users/sign_in',to: 'users#sign_in'
post 'users/create_session',to:'users#create_session'

 
root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#users_list' 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception

def hello
  #html="hello everybody"
  
  #return render html: html

end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  @user=User.all
if session[:user_id]
	@signed_in=User.find(session[:user_id])

end

  end
def new
@user=User.new
end
def create
User.create(name:params[:user][:name],age:params[:user][:age],email:params[:user][:email],password:params[:user][:password])

redirect_to action:'index'
end
def edit
@user=User.find(params[:id])

	end
	def update
	@user=User.find(params[:id])
@user.update(name:params[:user][:name],age:params[:user][:age],email:params[:user][:email],password:params[:user][:password])
redirect_to action:'index'
	end
def destroy
	@user=User.find(params[:id])
	@user.destroy
	redirect_to action:'index', notice: "your post is deleted"
end
def sign_out
	if !session[:user_id].blank?
		session.delete(:user_id)
	end
	redirect_to action: 'index'
def sign_in

end
def create_session
u=User.find_by(email: params[:email])
if(u.blank?)
	return redirect_to action: 'sign_in'
end
session
[:user_id]=u.id
redirect_to action: 'index'

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
  <% if @signed_in %>
<h4>WELCOME<%=@signed_in.email %></h4>
  	<%end%>
  </div>


    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f|%>
	<%=f.label:name%>
	<%=f.text_field:name%>
	<br>
	<%=f.label:age%>
	<%=f.number_field:age%>
	<br>
	<%=f.label:email%>
	<%=f.email_field:email%>
	<br>
	<%=f.label:password%>
	<%=f.password_field:password%>
<br>
<%=f.submit%>
	<%end%>

app/views/users/edit.html.erb
<h1>USER ENTRY DATA</h1>
<%=render 'form'%>

app/views/users/index.html.erb
<h1>HEY FOLKS :)</h1>

<%@user.each do |a|%>
<%=a.name%>
<br>
<%=link_to 'user_to_edit', '/user/2/edit'%>
<br>
<%=link_to 'delete', a, data: {confirm: "are you sure?"}, method: :delete%>
<%end%>

app/views/users/new.html.erb
<h1>USER SIGN UP</h1>
<%= form_for @user do |f|%>
	<%=f.label:name%>
	<%=f.text_field:name%>
	<br>
	<%=f.label:age%>
	<%=f.number_field:age%>
	<br>
	<%=f.label:email%>
	<%=f.email_field:email%>
	<br>
	<%=f.label:password%>
	<%=f.password_field:password%>
<br>
<%=f.submit%>
	<%end%>

app/views/users/sign_in.html.erb
<h1>USER SIGN IN</h1>

<%=form_tag users_create_session_path, method: :post do%>
<%= label_tag :email%>
<%=email_field_tag :email%>
<br>
<%=label_tag :password%>
<%=password_field_tag :password%>
<br>
<%=submit_tag "sign in"%>

	<%end%>